Repository lukaab/gitprojet, pull requests merged in 2025-02, with the labels that each got.

#16 [ADD]fichier1.txt résolution du probleme de la taille des cta
  fichier1.txt
Labels: bug

#17 [ADD]fichier3.txt ajout du fichier robot txt
  fichier3.txt
Labels: bug

#21 [ADD]fichier8.txt résolution du pb footer non cliquable
  file8.txt
Labels: bug

#20 [ADD]fichier9.txt résolution du pb couleur CTA conformité
  file9.txt
Labels: bug

#19 [ADD]fichier10.txt résolution du pb enregistrement SSL
  file10.txt
Labels: bug

#18 [ADD]fichier11.txt résolution du pb de variable d'environnemment vide
  file11.txt
Labels: bug

#24 [FIX]fichier12.txt résolution du pb du caroussel, il défile normaleme…
  file12.txt
Labels: bug

#26 [ADD]fichier13.txt résolution du pb déconnexion impossible
  file13.txt
Labels: bug

#25 [ADD]fichier14.txt résolution du pb connexion impossible
  textfile14.txt
Labels: bug

#28 Feature/18 ci lancement du linter
  .github/workflows/linter.yml
  test.js
Labels: enhancement

#30 [ADD]gitignore, ajout des fichiers de compilation pour le back en go et CI/CD
  .gitignore
Labels: enhancement

#32 [ADD]file5.txtmobile, code bouton mobile
  .gitignore
  eslint.config.cjs
  file5.txtBoutonMobile
  package-lock.json
  package.json
Labels: bug

#33 [ADD]fichier6.txt, ajout de la feature serveur
  file6.txt
Labels: enhancement

#34 [ADD]fichier7.txt, ajout du fichier afin de compenser l'image trop lo…
  file7.txt
Labels: enhancement

#35 [ADD]fichier15.txt, ajout du fichier afin de réparer le mailto qui ne…
  file15.txt
Labels: bug

#36 [ADD]fichier15.txt, ajout du fichier readme
  README.md
Labels: documentation

#37 [ADD]contributing.md, ajout du fichier contributing
  CONTRIBUTING.md
Labels: documentation
